"""empty message

Revision ID: 15df048a845b
Revises: 57ad059a8c2a
Create Date: 2022-11-23 16:13:49.554302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15df048a845b'
down_revision = '57ad059a8c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yesterday_task', sa.Text(), nullable=True),
    sa.Column('today_task', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
